version: "3.3"
services:
  pipedrive-task-service:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      NODE_ENV: development
      HTTP_PORT: 3000
      DEBUG_PORT: 3001
      PGUSER: teresalves 
      PGHOST: mydb 
      PGDATABASE: pipedriveDb 
      PGPASSWORD: example
      PGPORT: 5432 
    restart: unless-stopped
    volumes:
      - .:/app/
    networks:
      - pipedrive
    depends_on:
      - mydb
  mydb:
    container_name: "psql"
    image: postgres
    environment:
      POSTGRES_DB: pipedriveDb
      POSTGRES_USER: teresalves
      POSTGRES_PASSWORD: example
    ports:
      - 3300:5432
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - pipedrive
  

networks:
  pipedrive:
    driver: bridge
